#pragma once

#ifndef JACDAC_MAX_DEVICES
#define JACDAC_MAX_DEVICES 8
#endif
#ifndef JACDAC_MAX_SERVICES_PER_DEVICE
#define JACDAC_MAX_SERVICES_PER_DEVICE 16
#endif
#ifndef JACDAC_RX_QUEUE_SIZE
#define JACDAC_RX_QUEUE_SIZE 4
#endif
#ifndef JACDAC_TX_QUEUE_SIZE
#define JACDAC_TX_QUEUE_SIZE 4
#endif
#ifndef JACDAC_MAX_ACK_REQUESTS
#define JACDAC_MAX_ACK_REQUESTS 4
#endif
#ifndef JACDAC_MAX_REGISTER_REQUESTS
#define JACDAC_MAX_REGISTER_REQUESTS 4
#endif
#ifndef JACDAC_MAX_SUBSCRIBERS
#define JACDAC_MAX_SUBSCRIBERS 6
#endif
#ifndef JACDAC_FRAME_DATA_SIZE
#define JACDAC_FRAME_DATA_SIZE 240
#endif

#if JACDAC_MAX_DEVICES < 1 || JACDAC_MAX_DEVICES > 254
#error "JACDAC_MAX_DEVICES must be between 1 and 254"
#endif
#if JACDAC_MAX_SERVICES_PER_DEVICE < 1 || JACDAC_MAX_SERVICES_PER_DEVICE > 60
#error "JACDAC_MAX_SERVICES_PER_DEVICE must be between 1 and 60"
#endif
#if JACDAC_RX_QUEUE_SIZE < 1 || JACDAC_RX_QUEUE_SIZE > 254
#error "JACDAC_RX_QUEUE_SIZE must be between 1 and 254"
#endif
#if JACDAC_TX_QUEUE_SIZE < 1 || JACDAC_TX_QUEUE_SIZE > 254
#error "JACDAC_TX_QUEUE_SIZE must be between 1 and 254"
#endif
#if JACDAC_MAX_ACK_REQUESTS < 1 || JACDAC_MAX_ACK_REQUESTS > 254
#error "JACDAC_MAX_ACK_REQUESTS must be between 1 and 254"
#endif
#if JACDAC_MAX_REGISTER_REQUESTS < 1 || JACDAC_MAX_REGISTER_REQUESTS > 254
#error "JACDAC_MAX_REGISTER_REQUESTS must be between 1 and 254"
#endif
#if JACDAC_MAX_SUBSCRIBERS < 1 || JACDAC_MAX_SUBSCRIBERS > 254
#error "JACDAC_MAX_SUBSCRIBERS must be between 1 and 254"
#endif
#if JACDAC_FRAME_DATA_SIZE < 8 || JACDAC_FRAME_DATA_SIZE > 240 || (JACDAC_FRAME_DATA_SIZE % 4) != 0
#error "JACDAC_FRAME_DATA_SIZE must be a multiple of 4 between 8 and 240"
#endif